# Generated by Django 2.2.16 on 2022-09-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20220914_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Картинка, которая будет в после', upload_to='posts/', verbose_name='Картинка'),
        ),
    ]
